let predefinedStars = [
    // --- 4 
    "Basics of DOS",
    "Basics of Pascal",
    "Basics of Assembler - 13h",
    "Basics of electronics",
    // --- 5
    "Basics of C++",
    "Basics of algorithms",
    "Basics of networks",
    "HTML & CSS",
    "Basics of PHP",
    // --- 12
    "Data structures and algorithms",
    "C",
    "C++",
    "C#",
    "Java",
    "Embedded programming",
    "English C1",
    "Android",
    "PHP",
    "Basics of AI",
    "Linux",
    "Databases",
    // ---
    "Advanced PHP",
    "Advanced JavaScript", ,
    "Docker",
    "NodeJS",
    "MongoDB",
    "Spanish A2+",
    // ---
    "Advanced UML & OCL",
    "AI",
    "Parallel computing",
    "Testing",
    "Language processing",
    // ---
    "Advanced PHP",
    "Advanced MySQL",
    "Big Data",
    "Advanced Linux",
    "Python",
    "Queues",
    // ---
    "Advanced PHP",
    "Advanced SQL",
    "Advanced Python",
    "Advanced Docker",
];


let predefinedSpikes = [
    "Hard exams",
    "Maths",
    "Theory overload",
    "Complex Logic",
    "New Stack",
    "Eye Strain",
    "Big Refactor",
    "Brain Fog",
    "Late Hours",
    "Legacy Debt",
    "Deep Focus",
    "Edge Cases",
    "Mental Load",
    "System Migration",
    "Energy Drain",
    "Fixing Production",
    "Burnout Risk",
    "Strict Deadlines",
    "Sleepy Coder",
    "High Traffic",
    "No Strength",
    "API Bottlenecks",
    "Creative Block",
    "Security Patching",
    "Pure Exhaustion",
    "Code Review Loop",
    "Heavy Pressure",
    "Hard Debugging",
    "Out of Power",
    "Scalability Peak",
    "Total Fatigue",
    "Critical Update",
    "Need a Break"
];

export { predefinedStars, predefinedSpikes };